// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: lotus/lotus.proto

package lotus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specifies the type of index.
type IndexType int32

const (
	// Ordered index (maintains order).
	IndexType_INDEX_TYPE_ORDERED IndexType = 0
	// Unordered index (faster for lookups).
	IndexType_INDEX_TYPE_UNORDERED IndexType = 1
)

// Enum value maps for IndexType.
var (
	IndexType_name = map[int32]string{
		0: "INDEX_TYPE_ORDERED",
		1: "INDEX_TYPE_UNORDERED",
	}
	IndexType_value = map[string]int32{
		"INDEX_TYPE_ORDERED":   0,
		"INDEX_TYPE_UNORDERED": 1,
	}
)

func (x IndexType) Enum() *IndexType {
	p := new(IndexType)
	*p = x
	return p
}

func (x IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_lotus_lotus_proto_enumTypes[0].Descriptor()
}

func (IndexType) Type() protoreflect.EnumType {
	return &file_lotus_lotus_proto_enumTypes[0]
}

func (x IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexType.Descriptor instead.
func (IndexType) EnumDescriptor() ([]byte, []int) {
	return file_lotus_lotus_proto_rawDescGZIP(), []int{0}
}

// Specifies the format for encoding/decoding bytes data.
type FormatType int32

const (
	// Standard base64 encoding.
	FormatType_FORMAT_TYPE_BASE64 FormatType = 0
	// Hexadecimal encoding.
	FormatType_FORMAT_TYPE_HEX FormatType = 1
)

// Enum value maps for FormatType.
var (
	FormatType_name = map[int32]string{
		0: "FORMAT_TYPE_BASE64",
		1: "FORMAT_TYPE_HEX",
	}
	FormatType_value = map[string]int32{
		"FORMAT_TYPE_BASE64": 0,
		"FORMAT_TYPE_HEX":    1,
	}
)

func (x FormatType) Enum() *FormatType {
	p := new(FormatType)
	*p = x
	return p
}

func (x FormatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormatType) Descriptor() protoreflect.EnumDescriptor {
	return file_lotus_lotus_proto_enumTypes[1].Descriptor()
}

func (FormatType) Type() protoreflect.EnumType {
	return &file_lotus_lotus_proto_enumTypes[1]
}

func (x FormatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FormatType.Descriptor instead.
func (FormatType) EnumDescriptor() ([]byte, []int) {
	return file_lotus_lotus_proto_rawDescGZIP(), []int{1}
}

// Defines options for indexing a field.
type IndexOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of index (defaults to ordered).
	Type IndexType `protobuf:"varint,1,opt,name=type,proto3,enum=lotus.IndexType" json:"type,omitempty"`
	// Whether this is a unique index (defaults to false).
	Unique bool `protobuf:"varint,2,opt,name=unique,proto3" json:"unique,omitempty"`
}

func (x *IndexOption) Reset() {
	*x = IndexOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lotus_lotus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexOption) ProtoMessage() {}

func (x *IndexOption) ProtoReflect() protoreflect.Message {
	mi := &file_lotus_lotus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexOption.ProtoReflect.Descriptor instead.
func (*IndexOption) Descriptor() ([]byte, []int) {
	return file_lotus_lotus_proto_rawDescGZIP(), []int{0}
}

func (x *IndexOption) GetType() IndexType {
	if x != nil {
		return x.Type
	}
	return IndexType_INDEX_TYPE_ORDERED
}

func (x *IndexOption) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

// Defines options for indexing multiple fields.
type CompositeIndexesOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of composite indexes.
	Index []*CompositeIndexOption `protobuf:"bytes,1,rep,name=index,proto3" json:"index,omitempty"`
}

func (x *CompositeIndexesOption) Reset() {
	*x = CompositeIndexesOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lotus_lotus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompositeIndexesOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeIndexesOption) ProtoMessage() {}

func (x *CompositeIndexesOption) ProtoReflect() protoreflect.Message {
	mi := &file_lotus_lotus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeIndexesOption.ProtoReflect.Descriptor instead.
func (*CompositeIndexesOption) Descriptor() ([]byte, []int) {
	return file_lotus_lotus_proto_rawDescGZIP(), []int{1}
}

func (x *CompositeIndexesOption) GetIndex() []*CompositeIndexOption {
	if x != nil {
		return x.Index
	}
	return nil
}

// Defines options for composite indexes involving multiple fields.
type CompositeIndexOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of composite index (defaults to ordered).
	Type IndexType `protobuf:"varint,1,opt,name=type,proto3,enum=lotus.IndexType" json:"type,omitempty"`
	// Whether this is a unique index (defaults to false).
	Unique bool `protobuf:"varint,2,opt,name=unique,proto3" json:"unique,omitempty"`
	// List of field names involved in the composite index.
	Fields []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *CompositeIndexOption) Reset() {
	*x = CompositeIndexOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lotus_lotus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompositeIndexOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeIndexOption) ProtoMessage() {}

func (x *CompositeIndexOption) ProtoReflect() protoreflect.Message {
	mi := &file_lotus_lotus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeIndexOption.ProtoReflect.Descriptor instead.
func (*CompositeIndexOption) Descriptor() ([]byte, []int) {
	return file_lotus_lotus_proto_rawDescGZIP(), []int{2}
}

func (x *CompositeIndexOption) GetType() IndexType {
	if x != nil {
		return x.Type
	}
	return IndexType_INDEX_TYPE_ORDERED
}

func (x *CompositeIndexOption) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *CompositeIndexOption) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Defines options for how bytes fields are encoded/decoded.
type BytesOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Format to use for displaying binary data (defaults to base64).
	Format FormatType `protobuf:"varint,1,opt,name=format,proto3,enum=lotus.FormatType" json:"format,omitempty"`
}

func (x *BytesOption) Reset() {
	*x = BytesOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lotus_lotus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesOption) ProtoMessage() {}

func (x *BytesOption) ProtoReflect() protoreflect.Message {
	mi := &file_lotus_lotus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesOption.ProtoReflect.Descriptor instead.
func (*BytesOption) Descriptor() ([]byte, []int) {
	return file_lotus_lotus_proto_rawDescGZIP(), []int{3}
}

func (x *BytesOption) GetFormat() FormatType {
	if x != nil {
		return x.Format
	}
	return FormatType_FORMAT_TYPE_BASE64
}

// Defines options for how numeric fields are scaled/represented.
type NumericOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Total number of significant digits (including decimals).
	Precision *uint32 `protobuf:"varint,1,opt,name=precision,proto3,oneof" json:"precision,omitempty"`
	// Number of decimal places (0 for integers).
	Scale *uint32 `protobuf:"varint,2,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
}

func (x *NumericOption) Reset() {
	*x = NumericOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lotus_lotus_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumericOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericOption) ProtoMessage() {}

func (x *NumericOption) ProtoReflect() protoreflect.Message {
	mi := &file_lotus_lotus_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericOption.ProtoReflect.Descriptor instead.
func (*NumericOption) Descriptor() ([]byte, []int) {
	return file_lotus_lotus_proto_rawDescGZIP(), []int{4}
}

func (x *NumericOption) GetPrecision() uint32 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *NumericOption) GetScale() uint32 {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return 0
}

var file_lotus_lotus_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*CompositeIndexesOption)(nil),
		Field:         99001,
		Name:          "lotus.composite",
		Tag:           "bytes,99001,opt,name=composite",
		Filename:      "lotus/lotus.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*IndexOption)(nil),
		Field:         99001,
		Name:          "lotus.index",
		Tag:           "bytes,99001,opt,name=index",
		Filename:      "lotus/lotus.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*BytesOption)(nil),
		Field:         99002,
		Name:          "lotus.bytes",
		Tag:           "bytes,99002,opt,name=bytes",
		Filename:      "lotus/lotus.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*NumericOption)(nil),
		Field:         99003,
		Name:          "lotus.numeric",
		Tag:           "bytes,99003,opt,name=numeric",
		Filename:      "lotus/lotus.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// Option to specify composite indexes on multiple fields.
	//
	// optional lotus.CompositeIndexesOption composite = 99001;
	E_Composite = &file_lotus_lotus_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Option to mark a field as indexed.
	//
	// optional lotus.IndexOption index = 99001;
	E_Index = &file_lotus_lotus_proto_extTypes[1]
	// Option to specify how bytes fields are encoded/decoded.
	//
	// optional lotus.BytesOption bytes = 99002;
	E_Bytes = &file_lotus_lotus_proto_extTypes[2]
	// Option to specify how numeric fields are scaled/represented.
	//
	// optional lotus.NumericOption numeric = 99003;
	E_Numeric = &file_lotus_lotus_proto_extTypes[3]
)

var File_lotus_lotus_proto protoreflect.FileDescriptor

var file_lotus_lotus_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x2f, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x0b,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6c, 0x6f, 0x74, 0x75,
	0x73, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x22, 0x4b, 0x0a, 0x16, 0x43, 0x6f, 0x6d,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x6c, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6c,
	0x6f, 0x74, 0x75, 0x73, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x22, 0x38, 0x0a, 0x0b, 0x42, 0x79, 0x74, 0x65, 0x73, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x65,
	0x0a, 0x0d, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x48, 0x00, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x01, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a,
	0x0a, 0x5f, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x2a, 0x3d, 0x0a, 0x09, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x4e,
	0x44, 0x45, 0x58, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4f, 0x52, 0x44, 0x45, 0x52,
	0x45, 0x44, 0x10, 0x01, 0x2a, 0x39, 0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x42, 0x41, 0x53, 0x45, 0x36, 0x34, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x46, 0x4f,
	0x52, 0x4d, 0x41, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x48, 0x45, 0x58, 0x10, 0x01, 0x3a,
	0x61, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb9, 0x85,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x88,
	0x01, 0x01, 0x3a, 0x4c, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb9, 0x85, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x88, 0x01, 0x01,
	0x3a, 0x4c, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xba, 0x85, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x88, 0x01, 0x01, 0x3a, 0x52,
	0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xbb, 0x85, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x88,
	0x01, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x72, 0x79, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x6c, 0x6f, 0x74,
	0x75, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6c, 0x6f, 0x74, 0x75, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lotus_lotus_proto_rawDescOnce sync.Once
	file_lotus_lotus_proto_rawDescData = file_lotus_lotus_proto_rawDesc
)

func file_lotus_lotus_proto_rawDescGZIP() []byte {
	file_lotus_lotus_proto_rawDescOnce.Do(func() {
		file_lotus_lotus_proto_rawDescData = protoimpl.X.CompressGZIP(file_lotus_lotus_proto_rawDescData)
	})
	return file_lotus_lotus_proto_rawDescData
}

var file_lotus_lotus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_lotus_lotus_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_lotus_lotus_proto_goTypes = []interface{}{
	(IndexType)(0),                      // 0: lotus.IndexType
	(FormatType)(0),                     // 1: lotus.FormatType
	(*IndexOption)(nil),                 // 2: lotus.IndexOption
	(*CompositeIndexesOption)(nil),      // 3: lotus.CompositeIndexesOption
	(*CompositeIndexOption)(nil),        // 4: lotus.CompositeIndexOption
	(*BytesOption)(nil),                 // 5: lotus.BytesOption
	(*NumericOption)(nil),               // 6: lotus.NumericOption
	(*descriptorpb.MessageOptions)(nil), // 7: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 8: google.protobuf.FieldOptions
}
var file_lotus_lotus_proto_depIdxs = []int32{
	0,  // 0: lotus.IndexOption.type:type_name -> lotus.IndexType
	4,  // 1: lotus.CompositeIndexesOption.index:type_name -> lotus.CompositeIndexOption
	0,  // 2: lotus.CompositeIndexOption.type:type_name -> lotus.IndexType
	1,  // 3: lotus.BytesOption.format:type_name -> lotus.FormatType
	7,  // 4: lotus.composite:extendee -> google.protobuf.MessageOptions
	8,  // 5: lotus.index:extendee -> google.protobuf.FieldOptions
	8,  // 6: lotus.bytes:extendee -> google.protobuf.FieldOptions
	8,  // 7: lotus.numeric:extendee -> google.protobuf.FieldOptions
	3,  // 8: lotus.composite:type_name -> lotus.CompositeIndexesOption
	2,  // 9: lotus.index:type_name -> lotus.IndexOption
	5,  // 10: lotus.bytes:type_name -> lotus.BytesOption
	6,  // 11: lotus.numeric:type_name -> lotus.NumericOption
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	8,  // [8:12] is the sub-list for extension type_name
	4,  // [4:8] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_lotus_lotus_proto_init() }
func file_lotus_lotus_proto_init() {
	if File_lotus_lotus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lotus_lotus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lotus_lotus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompositeIndexesOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lotus_lotus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompositeIndexOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lotus_lotus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lotus_lotus_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumericOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lotus_lotus_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lotus_lotus_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_lotus_lotus_proto_goTypes,
		DependencyIndexes: file_lotus_lotus_proto_depIdxs,
		EnumInfos:         file_lotus_lotus_proto_enumTypes,
		MessageInfos:      file_lotus_lotus_proto_msgTypes,
		ExtensionInfos:    file_lotus_lotus_proto_extTypes,
	}.Build()
	File_lotus_lotus_proto = out.File
	file_lotus_lotus_proto_rawDesc = nil
	file_lotus_lotus_proto_goTypes = nil
	file_lotus_lotus_proto_depIdxs = nil
}
